Updated 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -8,14 +8,21 @@ if [[ "$#" -lt 4 ]]; then
 fi
 
 # Assign the arguments to variables for readability
-
-file_path=$1
+path_to_file=$1
 ip=$2
 username=$3
-ssh_key=$4
+path_to_ssh_key=$4
 
-# Disable strict host key checking for the ssh connection
-ssh_options="-o StrictHostKeyChecking=no"
+# transfer file using scp with strict host key checking disabled
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# check if the file transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "File transfer successful"
+else
+  echo "File transfer failed"
+fi
 
 # Use scp to transfer the file to the user's home directory on the remote server
 # -i option specifies the private key to use for authentication
@@ -23,5 +30,3 @@ ssh_options="-o StrictHostKeyChecking=no"
 # $file_path is the path to the file we want to transfer
 # $username@$ip specifies the user and IP of the remote server we want to transfer the file to
 # :~ specifies the user's home directory on the remote server
-
-scp -i "$ssh_key" $ssh_options "$file_path" "$username@$ip":~
