transfer file to server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,9 @@
 #!/usr/bin/env bash
 # checking for command line arguments
-
 if [ $# -lt 4 ]
-then 
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
 # assigning paramentals to variables
@@ -12,17 +11,16 @@ fi
 path_to_file=$1
 ip=$2
 username=$3
-path_to_shh_key=$4
+path_to_ssh_key=$4
+
 
 # disabbling strict host key checking
-
 scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
-
 
 # checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "FILE WAS TRANSFERED SUCCESSFULLY"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "FILE TRANSFER FAILED"
+  echo "FILE TRANSFER FAILED"
 fi
